version: '3'

services:
  postgres13:
    image: 'postgres:latest'
    
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: olist_database # The PostgreSQL default database (automatically created at first launch)
